user_login:
    pattern:  /login
    defaults: { _controller: CpAdminBundle:User:login }
    
login_check:
    pattern: /admin/check
    
admin_homepage:
    pattern: /admin
    defaults: { _controller: CpAdminBundle:Admin:index }

gerer_film:
    pattern: /admin/films
    defaults: { _controller: CpAdminBundle:Film:gerer }
    
ajouter_film:
    pattern: /admin/ajouter-film
    defaults: { _controller: CpAdminBundle:Film:ajouter }

editer_film:
    pattern: /admin/editer-film-{id}
    defaults: { _controller: CpAdminBundle:Film:editer }
    requirements:
      id: \d+

supprimer_film:
    pattern: /admin/supprimer-film-{id}
    defaults: { _controller: CpAdminBundle:Film:supprimer }
    requirements:
      id: \d+

gerer_programme:
    pattern: /admin/programmes
    defaults: { _controller: CpAdminBundle:Programme:gerer }

ajouter_programme:
    pattern: /admin/ajouter-programme
    defaults: { _controller: CpAdminBundle:Programme:ajouter }
    
editer_programme:
    pattern: /admin/editer-programme-{id}
    defaults: { _controller: CpAdminBundle:Programme:editer }
    requirements:
      id: \d+
      
supprimer_programme:
    pattern: /admin/supprimer-programme-{id}
    defaults: { _controller: CpAdminBundle:Programme:supprimer }
    requirements:
      id: \d+