parameters:
#    cp_admin.example.class: Cp\Bundle\AdminBundle\Example

services:
#    cp_admin.example:
#        class: %cp_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
