parameters:
#    cp_actu.example.class: Cp\Bundle\ActuBundle\Example

services:
#    cp_actu.example:
#        class: %cp_actu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
