CpContactBundle:
    resource: "@CpContactBundle/Resources/config/routing.yml"
    prefix:   /

CpAdminBundle:
    resource: "@CpAdminBundle/Resources/config/routing.yml"
    prefix:   /

CpActuBundle:
    resource: "@CpActuBundle/Resources/config/routing.yml"
    prefix:   /

CpProgrammeBundle:
    resource: "@CpProgrammeBundle/Resources/config/routing.yml"
    prefix:   /programme

CpFilmBundle:
    resource: "@CpFilmBundle/Resources/config/routing.yml"
    prefix:   /film

CpCoreBundle:
    resource: "@CpCoreBundle/Resources/config/routing.yml"
    prefix:   /

CpIndexBundle:
    resource: "@CpIndexBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
