parameters:
#    cp_core.example.class: Cp\Bundle\CoreBundle\Example

services:
#    cp_core.example:
#        class: %cp_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    core.sql_date:
        class: Cp\Bundle\CoreBundle\Service\SqlDateService