parameters:
#    cp_index.example.class: Cp\Bundle\IndexBundle\Example

services:
#    cp_index.example:
#        class: %cp_index.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
