parameters:
#    cp_seance.example.class: Cp\Bundle\SeanceBundle\Example

services:
#    cp_seance.example:
#        class: %cp_seance.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
