parameters:
#    cp_static.example.class: Cp\Bundle\StaticBundle\Example

services:
#    cp_static.example:
#        class: %cp_static.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
