parameters:
#    cp_programme.example.class: Cp\Bundle\ProgrammeBundle\Example

services:
#    cp_programme.example:
#        class: %cp_programme.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
