parameters:
#    cp_film.example.class: Cp\Bundle\FilmBundle\Example

services:
#    cp_film.example:
#        class: %cp_film.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
